
image: tmaier/docker-compose:latest

services:
  - docker:dind

stages:
  - install
  - build
  - test
  # - build-docker-compose
  
cache:
  paths:
    - node_modules/

Install Dependencies:
  image: node:12.4.0-alpine
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

Build:
  stage: build
  before_script:
    - docker info
    - docker-compose --version
  script:
    - docker-compose build

Test:
  stage: test
  before_script:
    - docker info
    - docker-compose --version
  script: 
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit
    - docker-compose down

# Build Docker Compose:
#   stage: build-docker-compose
#   before_script:
#     - apk add --no-cache py-pip
#     - pip install docker-compose
#   script: 
#     - docker-compose build
#     - docker-compose down
#     - docker-compose up -d --force-recreate