
image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

stages:
  - test
  - build-stage
  # - build-docker-compose

Test:
  stage: test
  script: 
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit
    - docker-compose down

Build Stage:
  stage: build-stage
  when: manual
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker-compose -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.prod.yml push
    - docker stack deploy preprod -c  docker-compose.prod.yml --with-registry-auth

# Build Docker Compose:
#   stage: build-docker-compose
#   before_script:
#     - apk add --no-cache py-pip
#     - pip install docker-compose
#   script: 
#     - docker-compose build
#     - docker-compose down
#     - docker-compose up -d --force-recreate