
image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

stages:
  - build
  - test
  # - build-docker-compose
  
cache:
  paths:
    - node_modules/

Install Dependencies:
  stage: build
  script:
    - npm install
    - docker-compose build
  artifacts:
    paths:
      - node_modules/

Test:
  stage: test
  script: 
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit
    - docker-compose down

# Build Docker Compose:
#   stage: build-docker-compose
#   before_script:
#     - apk add --no-cache py-pip
#     - pip install docker-compose
#   script: 
#     - docker-compose build
#     - docker-compose down
#     - docker-compose up -d --force-recreate