image: node:12.4.0-alpine

stages:
  - build
  # - test
  - deploy-stage
  
cache:
  paths:
    - node_modules/

Install Dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

# Test:
#   stage: test
#   before_script:
#     - cp .env.example .env
#     - cat .env
#   script: 
    - npm run test

Deploy Stage:
  stage: deploy-stage
  script: 
    - apk add --no-cache docker-compose
    - docker-compose -f docker-compose.yml up -d